# Generated by Django 3.2.5 on 2021-07-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telegram_id', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=20)),
                ('Username', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=20)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Is_registered', models.BooleanField(default=False)),
                ('Is_Driver', models.BooleanField(default=False)),
                ('Car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.car')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='Bot.province')),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('scheduled_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='Bot.user')),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='Bot.region')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='Bot.region')),
            ],
        ),
    ]
