# Generated by Django 3.2.5 on 2021-07-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Saved_Ads',
            field=models.ManyToManyField(to='Bot.Ads'),
        ),
    ]
