# Generated by Django 3.2.6 on 2021-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_user_saved_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='has_mail',
            field=models.BooleanField(default=False),
        ),
    ]
