# Generated by Django 3.2.6 on 2021-08-12 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_ads_has_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Joined_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
